### ISSUE TITLE
Ugoira animations are not playable

### ISSUE THREAD

**Issue by Kerobyte** [FreeNowOrg/PixivNow#26]
Example:
https://pixiv.wjghj.cn/artworks/101271612
https://www.pixiv.net/en/artworks/101271612

**Comment by dragon-fish** [comment]
Thank you for your feedback. This is because we have not yet achieved it.  
The most fundamental reason is that I didn't have such ability when I started writing this project.  
In addition, Ugoira will consume a lot of cf workers runtime. At present, my service is being disturbed by a large number of crawlers. I'm worried about whether I can bear the price.  
Maybe I will implement this function at some time. For example, someone is willing to provide me with technical or economic assistance :)

**Comment by dragon-fish** [comment]
I discovered that ugoira works by downloading a packed zip file containing all the frames of the animation. This may not bring a lot of additional consumption. Because workers are only charged based on the number of requests.

I will revisit this request.

**Comment by dragon-fish** [comment]
https://github.com/FreeNowOrg/PixivNow/assets/44761872/cb46b410-c8e8-4e81-bc94-5a749fae533a

Interesting...
